# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-26 20:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='text',
            field=models.TextField(default=''),
        ),
    ]
