# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-27 22:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0002_entity_text'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Entity',
            new_name='Entities',
        ),
    ]
